# T9 must score the entire appended word, not just its first characters.
# Generate a separate unit so other schemas retain upstream Octagram behavior.
set(T9_GRAMMAR_SOURCE "${CMAKE_SOURCE_DIR}/librime-octagram/src/octagram.cc")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${T9_GRAMMAR_SOURCE}")
file(READ "${T9_GRAMMAR_SOURCE}" T9_GRAMMAR_CODE)
function(t9_grammar_replace old new)
  string(FIND "${T9_GRAMMAR_CODE}" "${old}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Octagram changed: review T9 grammar anchor: ${old}")
  endif()
  string(REPLACE "${old}" "${new}" code "${T9_GRAMMAR_CODE}")
  set(T9_GRAMMAR_CODE "${code}" PARENT_SCOPE)
endfunction()
t9_grammar_replace("struct GrammarConfig {" "struct GrammarConfig {\n  bool full_word = false;")
t9_grammar_replace("    config->GetInt(\"grammar/collocation_max_length\"," "    config->GetBool(\"t9/joint_decoder\", &config_->full_word);\n    config->GetInt(\"grammar/collocation_max_length\",")
set(T9_GRAMMAR_ANCHOR "      const auto& match(matches[i]);")
string(FIND "${T9_GRAMMAR_CODE}" "${T9_GRAMMAR_ANCHOR}" T9_GRAMMAR_POS)
if(T9_GRAMMAR_POS EQUAL -1)
  message(FATAL_ERROR "Octagram changed: review whole-word scoring")
endif()
string(REPLACE "${T9_GRAMMAR_ANCHOR}" "${T9_GRAMMAR_ANCHOR}\n      if (config_->full_word && match.length != word_query.size()) continue;" T9_GRAMMAR_CODE "${T9_GRAMMAR_CODE}")
set(T9_GRAMMAR_COPY "${CMAKE_CURRENT_BINARY_DIR}/cyime-octagram.cc")
file(CONFIGURE OUTPUT "${T9_GRAMMAR_COPY}" CONTENT "${T9_GRAMMAR_CODE}" @ONLY)
get_target_property(T9_GRAMMAR_SOURCES rime-octagram-objs SOURCES)
set(T9_GRAMMAR_REPLACED FALSE)
foreach(T9_SOURCE IN LISTS T9_GRAMMAR_SOURCES)
  if(T9_SOURCE MATCHES "(^|/)octagram\\.cc$")
    list(REMOVE_ITEM T9_GRAMMAR_SOURCES "${T9_SOURCE}")
    set(T9_GRAMMAR_REPLACED TRUE)
  endif()
endforeach()
if(NOT T9_GRAMMAR_REPLACED)
  message(FATAL_ERROR "Cannot locate Octagram compilation unit")
endif()
list(APPEND T9_GRAMMAR_SOURCES "${T9_GRAMMAR_COPY}")
set_property(TARGET rime-octagram-objs PROPERTY SOURCES "${T9_GRAMMAR_SOURCES}")
target_include_directories(rime-octagram-objs PRIVATE "${CMAKE_SOURCE_DIR}/librime-octagram/src")
