# Build-local instrumentation of lookup dependencies. No dictionary/ranking
# policy changes and no pointers into a previous syllabifier are retained.
function(t9_trace_replace old new)
  string(FIND "${code}" "${old}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "librime lookup changed: review T9 dependency anchor: ${old}")
  endif()
  string(REPLACE "${old}" "${new}" updated "${code}")
  set(code "${updated}" PARENT_SCOPE)
endfunction()
foreach(unit dictionary table user_dictionary)
  set(source "${CMAKE_SOURCE_DIR}/librime/src/rime/dict/${unit}.cc")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" code)
  t9_trace_replace("#include <rime/common.h>" "#include <rime/common.h>\n#include <t9_lookup_trace.h>")
  if(unit STREQUAL "dictionary")
    t9_trace_replace("  const CodeMatch kFailed" "  T9ObserveExtra(current_pos);\n  const CodeMatch kFailed")
    t9_trace_replace("      collect_chunks(collector.get()," "      T9OriginScope origin(sv.first);\n      collect_chunks(collector.get(),")
  elseif(unit STREQUAL "table")
    t9_trace_replace("    size_t current_pos = item.current_pos;" "    size_t current_pos = item.current_pos;\n    T9ObservePosition(item.origin, current_pos);")
    t9_trace_replace("        size_t end_pos = props->end_pos;" "        size_t end_pos = props->end_pos;\n        T9ObservePosition(item.origin, end_pos);")
  else()
    t9_trace_replace("  auto index = syll_graph.indices.find(current_pos);" "  T9ObserveExtra(current_pos);\n  auto index = syll_graph.indices.find(current_pos);")
    t9_trace_replace("      auto next_index = syll_graph.indices.find(end_pos);" "      T9ObserveExtra(end_pos);\n      auto next_index = syll_graph.indices.find(end_pos);")
  endif()
  set(copy "${CMAKE_CURRENT_BINARY_DIR}/cyime-${unit}.cc")
  file(CONFIGURE OUTPUT "${copy}" CONTENT "${code}" @ONLY)
  get_target_property(sources rime-static SOURCES)
  set(replaced FALSE)
  foreach(old IN LISTS sources)
    if(old MATCHES "(^|/)rime/dict/${unit}\\.cc$")
      list(REMOVE_ITEM sources "${old}")
      set(replaced TRUE)
    endif()
  endforeach()
  if(NOT replaced)
    message(FATAL_ERROR "Cannot locate ${unit} compilation unit")
  endif()
  list(APPEND sources "${copy}")
  set_property(TARGET rime-static PROPERTY SOURCES "${sources}")
endforeach()
