# Keep ambiguous one-key T9 initials (3 = d/e/f) even when e is a full syllable.
# Patch a build-local copy: do not mutate the pinned librime submodule.
set(T9_SYLLABIFIER_SOURCE "${CMAKE_SOURCE_DIR}/librime/src/rime/algo/syllabifier.cc")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${T9_SYLLABIFIER_SOURCE}")
file(READ "${T9_SYLLABIFIER_SOURCE}" T9_SYLLABIFIER_CODE)
set(T9_PRUNE_OLD "(std::max)(graph->vertices[farthest], kFuzzySpelling);")
set(T9_PRUNE_NEW [=[(std::max)(graph->vertices[farthest],
          input.size() == 1 && input[0] >= '2' && input[0] <= '9'
              ? kAbbreviation : kFuzzySpelling);]=])
string(FIND "${T9_SYLLABIFIER_CODE}" "${T9_PRUNE_OLD}" T9_PRUNE_POS)
if(T9_PRUNE_POS EQUAL -1)
  message(FATAL_ERROR "librime syllabifier changed: review T9 single-key recall patch")
endif()
string(REPLACE "${T9_PRUNE_OLD}" "${T9_PRUNE_NEW}" T9_SYLLABIFIER_CODE "${T9_SYLLABIFIER_CODE}")
string(REPLACE "#include \"syllabifier.h\"" "#include <rime/algo/syllabifier.h>" T9_SYLLABIFIER_CODE "${T9_SYLLABIFIER_CODE}")
set(T9_SYLLABIFIER_COPY "${CMAKE_CURRENT_BINARY_DIR}/cyime-syllabifier.cc")
file(CONFIGURE OUTPUT "${T9_SYLLABIFIER_COPY}" CONTENT "${T9_SYLLABIFIER_CODE}" @ONLY)
get_target_property(T9_RIME_SOURCES rime-static SOURCES)
set(T9_REPLACED FALSE)
foreach(T9_SOURCE IN LISTS T9_RIME_SOURCES)
  if(T9_SOURCE MATCHES "(^|/)rime/algo/syllabifier\\.cc$")
    list(REMOVE_ITEM T9_RIME_SOURCES "${T9_SOURCE}")
    set(T9_REPLACED TRUE)
  endif()
endforeach()
if(NOT T9_REPLACED)
  message(FATAL_ERROR "Cannot locate librime syllabifier compilation unit")
endif()
list(APPEND T9_RIME_SOURCES "${T9_SYLLABIFIER_COPY}")
set_property(TARGET rime-static PROPERTY SOURCES "${T9_RIME_SOURCES}")